package eportfolium.com.karuta.model.bean;
// Generated 21 sept. 2017 22:13:39 by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.search.annotations.Indexed;

/**
 * PsConfiguration generated by hbm2java
 */
@Indexed
@Entity
@Table(name = "configuration")
@EntityListeners(AuditListener.class)
public class Configuration implements Serializable {

	private static final long serialVersionUID = 5200461758170838794L;

	private Long id;
	private String name;
	private String value;
	private Date modifDate;

	public Configuration() {
	}

	public Configuration(String name, Date modifDate) {
		this.name = name;
		this.modifDate = modifDate;
	}

	public Configuration(String name, String value, Date modifDate) {
		this.name = name;
		this.value = value;
		this.modifDate = modifDate;
	}

	public Configuration(Long id) {
		this.id = id;
	}

	@Id
	@Column(name = "id_configuration", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifDate", nullable = false, length = 26)
	public Date getModifDate() {
		return this.modifDate;
	}

	public void setModifDate(Date modifDate) {
		this.modifDate = modifDate;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Configuration other = (Configuration) obj;
		if (getId() == null) {
			if (other.getId() != null)
				return false;
		} else if (!getId().equals(other.getId()))
			return false;
		return true;
	}

}
