package eportfolium.com.karuta.model.bean;
// Generated 13 juin 2019 19:14:13 by Hibernate Tools 5.2.10.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CredentialGroupMembersId generated by hbm2java
 */
@Embeddable
public class CredentialGroupMembersId implements Serializable {

	private static final long serialVersionUID = 2800890235327047840L;

	private Long credentialGroupId;
	private Long credentialId;

	public CredentialGroupMembersId() {
	}

	public CredentialGroupMembersId(Long credentialGroup, Long credential) {
		this.credentialGroupId = credentialGroup;
		this.credentialId = credential;
	}

	@Column(name = "cg", nullable = false)
	public Long getCredentialGroupId() {
		return this.credentialGroupId;
	}

	public void setCredentialGroupId(Long cg) {
		this.credentialGroupId = cg;
	}

	@Column(name = "userid", nullable = false)
	public Long getCredentialId() {
		return this.credentialId;
	}

	public void setCredentialId(Long credential) {
		this.credentialId = credential;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((credentialGroupId == null) ? 0 : credentialGroupId.hashCode());
		result = prime * result + ((credentialId == null) ? 0 : credentialId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CredentialGroupMembersId other = (CredentialGroupMembersId) obj;
		if (credentialGroupId == null) {
			if (other.credentialGroupId != null)
				return false;
		} else if (!credentialGroupId.equals(other.credentialGroupId))
			return false;
		if (credentialId == null) {
			if (other.credentialId != null)
				return false;
		} else if (!credentialId.equals(other.credentialId))
			return false;
		return true;
	}

}
