package eportfolium.com.karuta.model.bean;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.search.annotations.Indexed;

/**
 * CredentialGroup generated by hbm2java
 */
@Indexed
@Entity
@Table(name = "credential_group")
//@TableGenerator(name = "credential_group_table", initialValue = 0, allocationSize = 2)
public class CredentialGroup implements Serializable {

	private static final long serialVersionUID = 4410322160810429501L;

	private Long id;
	private String label;
	private Set<CredentialGroupMembers> members = new HashSet<CredentialGroupMembers>(0);

	public CredentialGroup() {
	}

	public CredentialGroup(Long id) {
		this.id = id;
	}

	public CredentialGroup(Long id, String label) {
		this.id = id;
		this.label = label;
	}

//	@DocumentId
	@Id
//	@GeneratedValue(strategy = GenerationType.TABLE, generator = "credential_group_table")
	@Column(name = "cg", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "label", unique = true, nullable = false)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "credentialGroup")
	public Set<CredentialGroupMembers> getMembers() {
		return members;
	}

	public void setMembers(Set<CredentialGroupMembers> members) {
		this.members = members;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CredentialGroup other = (CredentialGroup) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
