package eportfolium.com.karuta.model.bean;
// Generated 13 juin 2019 19:14:13 by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * DataTable generated by hbm2java
 */
@Entity
@Table(name = "data_table")
public class DataTable implements Serializable {

	private static final long serialVersionUID = -3258271925946548727L;

	private UUID id;
	private long owner;
	private long creator;
	private String type;
	private String mimetype;
	private String filename;
	private Long CDate;
	private byte[] data;

	public DataTable() {
	}

	public DataTable(UUID id, long owner, long creator, String type) {
		this.id = id;
		this.owner = owner;
		this.creator = creator;
		this.type = type;
	}

	public DataTable(UUID id, long owner, long creator, String type, String mimetype, String filename, Long CDate,
			byte[] data) {
		this.id = id;
		this.owner = owner;
		this.creator = creator;
		this.type = type;
		this.mimetype = mimetype;
		this.filename = filename;
		this.CDate = CDate;
		this.data = data;
	}

	@Id
	@GenericGenerator(name = "uuid2", strategy = "uuid2")
	@GeneratedValue(generator = "uuid2")
	@Column(name = "id", unique = true, nullable = false)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@Column(name = "owner", nullable = false)
	public long getOwner() {
		return this.owner;
	}

	public void setOwner(long owner) {
		this.owner = owner;
	}

	@Column(name = "creator", nullable = false)
	public long getCreator() {
		return this.creator;
	}

	public void setCreator(long creator) {
		this.creator = creator;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "mimetype")
	public String getMimetype() {
		return this.mimetype;
	}

	public void setMimetype(String mimetype) {
		this.mimetype = mimetype;
	}

	@Column(name = "filename")
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "c_date")
	public Long getCDate() {
		return this.CDate;
	}

	public void setCDate(Long CDate) {
		this.CDate = CDate;
	}

	@Column(name = "data")
	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DataTable other = (DataTable) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
