/* =======================================================
	Copyright 2020 - ePortfolium - Licensed under the
	Educational Community License, Version 2.0 (the "License"); you may
	not use this file except in compliance with the License. You may
	obtain a copy of the License at

	http://www.osedu.org/licenses/ECL-2.0

	Unless required by applicable law or agreed to in writing,
	software distributed under the License is distributed on an "AS IS"
	BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
	or implied. See the License for the specific language governing
	permissions and limitations under the License.
   ======================================================= */

package eportfolium.com.karuta.model.bean;
// Generated 13 juin 2019 19:14:13 by Hibernate Tools 5.2.10.Final

import java.io.Serializable;

import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * GroupGroup generated by hbm2java
 */
@Entity
@Table(name = "group_group")
@AssociationOverrides({
		@AssociationOverride(name = "id.group", joinColumns = @JoinColumn(name = "group", referencedColumnName = "gid", nullable = false)),
		@AssociationOverride(name = "id.childGroup", joinColumns = @JoinColumn(name = "child_group", referencedColumnName = "gid", nullable = false)) })
public class GroupGroup implements Serializable {

	private static final long serialVersionUID = 4099191465770302244L;

	private GroupGroupId id;

	public GroupGroup() {
	}

	public GroupGroup(GroupGroupId id) {
		this.id = id;
	}

	@EmbeddedId
	public GroupGroupId getId() {
		return this.id;
	}

	public void setId(GroupGroupId id) {
		this.id = id;
	}

	@Transient
	public GroupInfo getGroup() {
		return getId().getGroup();
	}

	public void setGroup(GroupInfo group) {
		getId().setGroup(group);
	}

	@Transient
	public GroupInfo getChildGroup() {
		return getId().getChildGroup();
	}

	public void setChildGroup(GroupInfo childGroup) {
		getId().setChildGroup(childGroup);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;

		GroupGroup that = (GroupGroup) o;

		if (getId() != null ? !getId().equals(that.getId()) : that.getId() != null)
			return false;

		return true;
	}

	@Override
	public int hashCode() {
		return (getId() != null ? getId().hashCode() : 0);
	}

}
