package eportfolium.com.karuta.model.bean;
// Generated 13 juin 2019 19:14:13 by Hibernate Tools 5.2.10.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupGroupId generated by hbm2java
 */
@Embeddable
public class GroupGroupId implements Serializable {

	private static final long serialVersionUID = 2095885409926253640L;

	private Long groupId;
	private Long childGroupId;

	public GroupGroupId() {
	}

	public GroupGroupId(Long group, Long childGroup) {
		this.groupId = group;
		this.childGroupId = childGroup;
	}

	@Column(name = "gid", nullable = false)
	public Long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Long group) {
		this.groupId = group;
	}

	@Column(name = "child_gid", nullable = false)
	public Long getChildGroupId() {
		return this.childGroupId;
	}

	public void setChildGroupId(Long childGroup) {
		this.childGroupId = childGroup;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((childGroupId == null) ? 0 : childGroupId.hashCode());
		result = prime * result + ((groupId == null) ? 0 : groupId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		GroupGroupId other = (GroupGroupId) obj;
		if (childGroupId == null) {
			if (other.childGroupId != null)
				return false;
		} else if (!childGroupId.equals(other.childGroupId))
			return false;
		if (groupId == null) {
			if (other.groupId != null)
				return false;
		} else if (!groupId.equals(other.groupId))
			return false;
		return true;
	}

}
