package eportfolium.com.karuta.model.bean;
// Generated 13 juin 2019 19:14:13 by Hibernate Tools 5.2.10.Final

import java.io.Serializable;

import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * GroupGroup generated by hbm2java
 */
@Entity
@Table(name = "group_group")
@AssociationOverrides({
		@AssociationOverride(name = "id.group", joinColumns = @JoinColumn(name = "group", referencedColumnName = "gid", nullable = false)),
		@AssociationOverride(name = "id.childGroup", joinColumns = @JoinColumn(name = "child_group", referencedColumnName = "gid", nullable = false)) })
public class GroupGroup implements Serializable {

	private static final long serialVersionUID = 4099191465770302244L;

	private GroupGroupId id;

	public GroupGroup() {
	}

	public GroupGroup(GroupGroupId id) {
		this.id = id;
	}

	@EmbeddedId
	public GroupGroupId getId() {
		return this.id;
	}

	public void setId(GroupGroupId id) {
		this.id = id;
	}

	@Transient
	public GroupInfo getGroup() {
		return getId().getGroup();
	}

	public void setGroup(GroupInfo group) {
		getId().setGroup(group);
	}

	@Transient
	public GroupInfo getChildGroup() {
		return getId().getChildGroup();
	}

	public void setChildGroup(GroupInfo childGroup) {
		getId().setChildGroup(childGroup);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		GroupGroup other = (GroupGroup) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
