package eportfolium.com.karuta.model.bean;
// Generated 13 juin 2019 19:14:13 by Hibernate Tools 5.2.10.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupRightsId generated by hbm2java
 */
@Embeddable
public class GroupRightsId implements Serializable {

	private static final long serialVersionUID = 7042573400581202433L;

	private String id; // Association with Node entity ?
	private Long groupRightInfoId;

	public GroupRightsId() {
	}

	public GroupRightsId(Long groupRightInfoId, String id) {
		this.groupRightInfoId = groupRightInfoId;
		this.id = id;
	}

	@Column(name = "grid", nullable = false)
	public Long getGroupRightInfoId() {
		return this.groupRightInfoId;
	}

	public void setGroupRightInfoId(Long groupRightInfoId) {
		this.groupRightInfoId = groupRightInfoId;
	}

	@Column(name = "id", nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((groupRightInfoId == null) ? 0 : groupRightInfoId.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		GroupRightsId other = (GroupRightsId) obj;
		if (groupRightInfoId == null) {
			if (other.groupRightInfoId != null)
				return false;
		} else if (!groupRightInfoId.equals(other.groupRightInfoId))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
