package eportfolium.com.karuta.model.bean;
// Generated 13 juin 2019 19:14:13 by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.UUID;

import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * GroupRights generated by hbm2java
 */
@Entity
@Table(name = "group_rights")
@AssociationOverrides({
		@AssociationOverride(name = "id.groupRightInfo", joinColumns = @JoinColumn(name = "grid", nullable = false)) })
public class GroupRights implements Serializable {

	private static final long serialVersionUID = 7563709378804723952L;

	public static final String NONE = "none";
	public static final String ADD = "add";
	public static final String READ = "read";
	public static final String WRITE = "write";
	public static final String SUBMIT = "submit";
	public static final String DELETE = "delete";
	public static final String LIER = "lier";
	public static final String DELIER = "delier";

	private GroupRightsId id;
	private boolean read;
	private boolean write;
	private boolean delete;
	private boolean submit;
	private boolean add;
	private String typesId;
	private String rulesId;
	private String notifyRoles;

	public GroupRights() {
	}

	public GroupRights(boolean read, boolean write, boolean delete, boolean submit) {
		this.read = read;
		this.write = write;
		this.delete = delete;
		this.submit = submit;
	}

	public GroupRights(GroupRightsId id, boolean read, boolean write, boolean delete, boolean submit, boolean add) {
		this.id = id;
		this.read = read;
		this.write = write;
		this.delete = delete;
		this.submit = submit;
		this.add = add;
	}

	public GroupRights(GroupRightsId id, boolean read, boolean write, boolean delete, boolean submit, boolean ad,
			String typesId, String rulesId, String notifyRoles) {
		this.id = id;
		this.read = read;
		this.write = write;
		this.delete = delete;
		this.submit = submit;
		this.add = ad;
		this.typesId = typesId;
		this.rulesId = rulesId;
		this.notifyRoles = notifyRoles;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)) })
	public GroupRightsId getId() {
		return this.id;
	}

	public void setId(GroupRightsId id) {
		this.id = id;
	}

	@Column(name = "RD", nullable = false)
	public boolean isRead() {
		return this.read;
	}

	public void setRead(boolean rd) {
		this.read = rd;
	}

	@Column(name = "WR", nullable = false)
	public boolean isWrite() {
		return this.write;
	}

	public void setWrite(boolean wr) {
		this.write = wr;
	}

	@Column(name = "DL", nullable = false)
	public boolean isDelete() {
		return this.delete;
	}

	public void setDelete(boolean dl) {
		this.delete = dl;
	}

	@Column(name = "SB", nullable = false)
	public boolean isSubmit() {
		return this.submit;
	}

	public void setSubmit(boolean sb) {
		this.submit = sb;
	}

	@Column(name = "AD", nullable = false)
	public boolean isAdd() {
		return this.add;
	}

	public void setAdd(boolean add) {
		this.add = add;
	}

	@Column(name = "types_id", length = 65535)
	public String getTypesId() {
		return this.typesId;
	}

	public void setTypesId(String typesId) {
		this.typesId = typesId;
	}

	@Column(name = "rules_id", length = 65535)
	public String getRulesId() {
		return this.rulesId;
	}

	public void setRulesId(String rulesId) {
		this.rulesId = rulesId;
	}

	@Column(name = "notify_roles", length = 65535)
	public String getNotifyRoles() {
		return this.notifyRoles;
	}

	public void setNotifyRoles(String notifyRoles) {
		this.notifyRoles = notifyRoles;
	}

	@Transient
	public GroupRightInfo getGroupRightInfo() {
		return getId().getGroupRightInfo();
	}

	public void setGroupRightInfo(GroupRightInfo groupRightInfo) {
		getId().setGroupRightInfo(groupRightInfo);
	}

	@Transient
	public UUID getGroupRightsId() {
		return getId().getId();
	}

	public void setGroupRightsId(UUID id) {
		getId().setId(id);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;

		GroupRights that = (GroupRights) o;

		if (getId() != null ? !getId().equals(that.getId()) : that.getId() != null)
			return false;

		return true;
	}

	@Override
	public int hashCode() {
		return (getId() != null ? getId().hashCode() : 0);
	}

}
