package eportfolium.com.karuta.model.bean;
// Generated 13 juin 2019 19:14:13 by Hibernate Tools 5.2.10.Final

import java.io.Serializable;

import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;

/**
 * GroupUserId generated by hbm2java
 */
@Embeddable
public class GroupUserId implements Serializable {

	private static final long serialVersionUID = 1429371866343044207L;

	private GroupInfo groupInfo;
	private Credential credential;

	public GroupUserId() {
	}

	public GroupUserId(GroupInfo groupInfo, Credential credential) {
		this.groupInfo = groupInfo;
		this.credential = credential;
	}

	@ManyToOne
	public GroupInfo getGroupInfo() {
		return this.groupInfo;
	}

	public void setGroupInfo(GroupInfo groupInfo) {
		this.groupInfo = groupInfo;
	}

	@ManyToOne
	public Credential getCredential() {
		return this.credential;
	}

	public void setCredential(Credential credential) {
		this.credential = credential;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((credential == null) ? 0 : credential.hashCode());
		result = prime * result + ((groupInfo == null) ? 0 : groupInfo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		GroupUserId other = (GroupUserId) obj;
		if (credential == null) {
			if (other.credential != null)
				return false;
		} else if (!credential.equals(other.credential))
			return false;
		if (groupInfo == null) {
			if (other.groupInfo != null)
				return false;
		} else if (!groupInfo.equals(other.groupInfo))
			return false;
		return true;
	}

}
