package eportfolium.com.karuta.model.bean;
// Generated 13 juin 2019 19:14:13 by Hibernate Tools 5.2.10.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupUserId generated by hbm2java
 */
@Embeddable
public class GroupUserId implements Serializable {

	private static final long serialVersionUID = 1429371866343044207L;

	private Long groupInfoId;
	private Long credentialId;

	public GroupUserId() {
	}

	public GroupUserId(long groupInfoId, long credentialId) {
		this.groupInfoId = groupInfoId;
		this.credentialId = credentialId;
	}

	@Column(name = "gid", nullable = false)
	public Long getGroupInfoId() {
		return this.groupInfoId;
	}

	public void setGroupInfoId(long groupInfo) {
		this.groupInfoId = groupInfo;
	}

	@Column(name = "userid", nullable = false)
	public Long getCredentialId() {
		return this.credentialId;
	}

	public void setCredentialId(long credential) {
		this.credentialId = credential;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((credentialId == null) ? 0 : credentialId.hashCode());
		result = prime * result + ((groupInfoId == null) ? 0 : groupInfoId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		GroupUserId other = (GroupUserId) obj;
		if (credentialId == null) {
			if (other.credentialId != null)
				return false;
		} else if (!credentialId.equals(other.credentialId))
			return false;
		if (groupInfoId == null) {
			if (other.groupInfoId != null)
				return false;
		} else if (!groupInfoId.equals(other.groupInfoId))
			return false;
		return true;
	}

}
