package eportfolium.com.karuta.model.bean;
// Generated 13 juin 2019 19:14:13 by Hibernate Tools 5.2.10.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PortfolioGroupMembersId generated by hbm2java
 */
@Embeddable
public class PortfolioGroupMembersId implements Serializable {

	private static final long serialVersionUID = -549500884031324847L;

	private Long portfolioGroupId;
	private String portfolioId;

	public PortfolioGroupMembersId() {
	}

	public PortfolioGroupMembersId(long portfolioGroupId, String portfolioId) {
		this.portfolioGroupId = portfolioGroupId;
		this.portfolioId = portfolioId;
	}

	@Column(name = "pg", nullable = false)
	public Long getPortfolioGroupId() {
		return this.portfolioGroupId;
	}

	public void setPortfolioGroupId(Long portfolioGroupId) {
		this.portfolioGroupId = portfolioGroupId;
	}

	@Column(name = "portfolio_id", nullable = false, length = 36)
	public String getPortfolioId() {
		return this.portfolioId;
	}

	public void setPortfolioId(String portfolioId) {
		this.portfolioId = portfolioId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((portfolioGroupId == null) ? 0 : portfolioGroupId.hashCode());
		result = prime * result + ((portfolioId == null) ? 0 : portfolioId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PortfolioGroupMembersId other = (PortfolioGroupMembersId) obj;
		if (portfolioGroupId == null) {
			if (other.portfolioGroupId != null)
				return false;
		} else if (!portfolioGroupId.equals(other.portfolioGroupId))
			return false;
		if (portfolioId == null) {
			if (other.portfolioId != null)
				return false;
		} else if (!portfolioId.equals(other.portfolioId))
			return false;
		return true;
	}

}
