package eportfolium.com.karuta.model.bean;
// Generated 13 juin 2019 19:14:13 by Hibernate Tools 5.2.10.Final

import java.io.Serializable;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;

/**
 * PortfolioGroupMembers generated by hbm2java
 */
@Entity
@Table(name = "portfolio_group_members")
public class PortfolioGroupMembers implements Serializable {

	private static final long serialVersionUID = 7694077274860630934L;

	private PortfolioGroupMembersId id;
	private Portfolio portfolio;
	private PortfolioGroup portfolioGroup;

	public PortfolioGroupMembers() {
	}

	public PortfolioGroupMembers(PortfolioGroupMembersId id) {
		this.id = id;
	}

	@EmbeddedId
	public PortfolioGroupMembersId getId() {
		return this.id;
	}

	public void setId(PortfolioGroupMembersId id) {
		this.id = id;
	}

	@ManyToOne
	@MapsId("portfolioGroupId")
	@JoinColumn(name = "pg", nullable = false, insertable = false, updatable = false)
	public PortfolioGroup getPortfolioGroup() {
		return portfolioGroup;
	}

	public void setPortfolioGroup(PortfolioGroup pg) {
		this.portfolioGroup = pg;
	}

	@ManyToOne
	@MapsId("portfolioId")
	@JoinColumn(name = "portfolio_id", nullable = false, insertable = false, updatable = false)
	public Portfolio getPortfolio() {
		return portfolio;
	}

	public void setPortfolio(Portfolio portfolio) {
		this.portfolio = portfolio;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;

		PortfolioGroupMembers that = (PortfolioGroupMembers) o;

		if (getId() != null ? !getId().equals(that.getId()) : that.getId() != null)
			return false;

		return true;
	}

	@Override
	public int hashCode() {
		return (getId() != null ? getId().hashCode() : 0);
	}

}
